### ISSUE TITLE
请问我是否可以放到pacakge里面直接编译

### ISSUE THREAD

**Issue by ddqp** [MuJJus/doghole#1]
我准备放到固件里面，所以直接clone到openwrt/package里面，然后menuconfig选中，然后编译，
这样是不是就可以直接继承进去了？

**Comment by ddqp** [comment]
用了你的doghole，的确不错，似乎路由更自由了，那个Doghole - 自定义 Dnsmasq,是说，我设置的网址或者ip，走哪种规则呢？

**Comment by MuJJus** [comment]
是可以集成的，注意依赖即可

附加的域名是指需要代理的地址

**Comment by ddqp** [comment]
好的，谢谢！！

**Comment by ddqp** [comment]
用了几天了，doghole，好评！！

doghole可以配合 shadowsocks吗？

**Comment by MuJJus** [comment]
在全局设置中有透明代理选项，配合 ss-redir 使用即可。

**Comment by ddqp** [comment]
好的，谢谢！
